name: SUPERHOT
version: ${project.version}
main: net.kunmc.lab.superhot.Superhot
api-version: 1.16
depend: [ ProtocolLib ]
commands:
  superhot:
    usage: |-
      /superhot start <player>
      /superhot stop
      /superhot config <configItem> <value>
      /superhot give <target> <item> [amount]
    default: op